// Generated by CoffeeScript 1.3.3
var Logger;

Logger = module.exports = function(currentStream) {
  return {
    stream: currentStream != null ? currentStream : '',
    log: function(args) {
      return this.stream += "" + args + "\n";
    }
  };
};
